{ debit: 2,
    train_number: '12025',
    position: 'Train has reached Destination and late by 0 minutes.',
    response_code: 200,
    route:
     [ { station_: [Object],
         actdep: '05:50',
         scharr_date: '17 Sep 2017',
         has_departed: true,
         station: [Object],
         actarr: '00:00',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '0 mins late',
         distance: 0,
         no: 1,
         has_arrived: true,
         latemin: 0,
         schdep: '05:50',
         scharr: 'Source' },
       { station_: [Object],
         actdep: '09:28',
         scharr_date: '17 Sep 2017',
         has_departed: true,
         station: [Object],
         actarr: '09:25',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '15 mins late',
         distance: 262,
         no: 2,
         has_arrived: true,
         latemin: 15,
         schdep: '09:13',
         scharr: '09:10' },
       { station_: [Object],
         actdep: '11:05',
         scharr_date: '17 Sep 2017',
         has_departed: true,
         station: [Object],
         actarr: '11:04',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '24 mins late',
         distance: 375,
         no: 3,
         has_arrived: true,
         latemin: 24,
         schdep: '10:42',
         scharr: '10:40' },
       { station_: [Object],
         actdep: '11:40',
         scharr_date: '17 Sep 2017',
         has_departed: true,
         station: [Object],
         actarr: '11:36',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '9 mins late',
         distance: 412,
         no: 4,
         has_arrived: true,
         latemin: 9,
         schdep: '11:30',
         scharr: '11:27' },
       { station_: [Object],
         actdep: '12:36',
         scharr_date: '17 Sep 2017',
         has_departed: true,
         station: [Object],
         actarr: '12:35',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '31 mins late',
         distance: 482,
         no: 5,
         has_arrived: true,
         latemin: 31,
         schdep: '12:05',
         scharr: '12:04' },
       { station_: [Object],
         actdep: '13:11',
         scharr_date: '17 Sep 2017',
         has_departed: true,
         station: [Object],
         actarr: '13:10',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '26 mins late',
         distance: 524,
         no: 6,
         has_arrived: true,
         latemin: 26,
         schdep: '12:45',
         scharr: '12:44' },
       { station_: [Object],
         actdep: '13:43',
         scharr_date: '17 Sep 2017',
         has_departed: false,
         station: [Object],
         actarr: '13:42',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '3 mins late',
         distance: 591,
         no: 7,
         has_arrived: false,
         latemin: 3,
         schdep: '13:40',
         scharr: '13:39' },
       { station_: [Object],
         actdep: '00:00',
         scharr_date: '17 Sep 2017',
         has_departed: false,
         station: [Object],
         actarr: '14:20',
         actarr_date: '17 Sep 2017',
         day: 0,
         status: '0 mins late',
         distance: 597,
         no: 8,
         has_arrived: true,
         latemin: 0,
         schdep: 'Destination',
         scharr: '14:20' } ],
    start_date: '17 Sep 2017',
    current_station:
     { station_: { code: 'SC', name: 'SECUNDERABAD JN' },